apiVersion: pps.pachyderm.io/v1
kind: Pipeline
metadata:
  name: pipeline-sample
spec:
  # pipeline:
  #  name: wordcount
  transform:
    image: pachyderm/opencv
    cmd:
    - "python3"
    - "/edges.py"
  input:
    pfs:
      repo: images
      glob: "/*"
