apiVersion: pps.pachyderm.io/v1
kind: Pipeline
metadata:
  name: pipeline-sample
spec:
  # pipeline:
  #  name: wordcount
  transform:
    image: wordcount-image
    cmd:
    - "/binary"
    - "/pfs/data"
    - "/pfs/out"
  input:
    pfs:
      repo: data
      glob: "/*"
